services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      LOG_FILE: dev-log-otro.txt
    links:
      - db
  db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data: